### PR TITLE
release 3.8.0

### PR DESCRIPTION
**Pull request by brookehus**

### CODE REVIEW

**Comment by brookehus** [comment]
Any thoughts on this issue with travis build 5.4?

```
Exceeded max retries, giving upWARNING conda_build.build:create_env(721): failed to create env, retrying.  exception was: Lock error: 

LOCKERROR: It looks like conda is already doing something.

The lock ['/Users/travis/miniconda3/pkgs/pyhmc-0.1.2-np112py35_0.tar.bz2.pid3096.conda_lock'] was found. Wait for it to finish before continuing.

If you are sure that conda is not running, remove it and try again.

You can also use: $ conda clean --lock
```

**Comment by mpharrigan** [comment]
I have no idea

**Comment by brookehus** [comment]
can you restart builds or give me permissions so i can see if it happens again

**Comment by mpharrigan** [comment]
I had already restarted it once. I just restarted it again. Maybe there's something wrong with that pyhmc package? Maybe the lock file somehow got packaged in which would be lol

**Comment by mpharrigan** [comment]
Just gonna merge it and maybe we won't have a package for that particular combo on osx

**Pull request merged**
